### ISSUE TITLE
Add actions

### ISSUE THREAD

**Issue by Robinlovelace** [cruse-bike/paper#1]

**Comment by Robinlovelace** [comment]
Heads-up @Hussein-Mahfouz it works! https://cruse-bike.github.io/paper/paper Not finished yet but hope that adding actions will be quick and easy...

**Comment by Robinlovelace** [comment]
Job done: https://github.com/cruse-bike/paper/tree/gh-pages

**Comment by Hussein-Mahfouz** [comment]
It looks great! I'll need to go over the code to learn how it works - I've never actually added actions so this is new to me
