### ISSUE TITLE
Port CycleStreets' input into manuscript source code

### ISSUE THREAD

**Issue by Robinlovelace** [cruse-bike/paper#17]
Heads-up @mvl22 the .tex doc is generated by the .qmd.
Will port now.

**Comment by mvl22** [comment]
Ah, sorry, didn't recognise . qmd as being a text file - was looking for .Rmd so then assumed you were just using .tex directly.

**Comment by Robinlovelace** [comment]
No problems @mvl22 and thanks for the addition. Any other comments/changes welcome.
