### ISSUE TITLE
Paper is failing to compile

### ISSUE THREAD

**Issue by Robinlovelace** [cruse-bike/paper#40]
With the following message.

I think this may be related to issues mentioned by @eugenividal:

```
Undefined control sequence.
l.650 Data\n
            ; Geodirectory categories for `Tertiary Education' and `Other 

see /home/robin/github/cruse-bike/cruse-paper/paper.log for more information.
```

**Comment by eugenividal** [comment]
Hi @Robinlovelace. Sorry to see this. Not sure if it is the same. I had issues related to the bibliography. I tried to fix it by changing `bibliography.bib` with `references.bib` but it did not work.

**Comment by Robinlovelace** [comment]
Fixed now.
