### ISSUE TITLE
Cycling uptake leads to less trips overall - Reference

### ISSUE THREAD

**Issue by Hussein-Mahfouz** [cruse-bike/paper#5]
From your draft

> Although cycling uptake appears on the surface to only relate to the ‘shift’ part of the ASI framework, closer consideration of the knock-on impacts of cycling uptake shows that it can also help avoid unnecessary trips [citation needed, any ideas Hussein?]

The one phenomenom that came to mind is traffic evaporation. This is a quote from our cycle-networks paper

> `Safeguarding against increased car traffic may be counter-productive if the goal is to create a mode-shift, as research has shown that reducing road space for cars leads to less cars on the road, a phenomenon referred to as “traffic evaporation” (Nello-Deakin, 2020).`

This is the paper cited: [Environmental determinants of cycling: Not seeing the forest for the trees?](https://www.sciencedirect.com/science/article/pii/S0966692319309974)

@Robinlovelace  is that what you had in mind? I'll look for other references

**Comment by Robinlovelace** [comment]
That looks perfect!
