### ISSUE TITLE
National overview map?

### ISSUE THREAD

**Issue by Robinlovelace** [cruse-bike/paper#7]
Wonder if it's worth adding an overview map, perhaps with county borders and zones coloured by % cycling? Thoughts @Hussein-Mahfouz it could be a fun one..

This is where I'm at with the results, pretty happy with them so far:

![image](https://github.com/cruse-bike/paper/assets/1825120/ad04d621-bcbe-4550-8c20-bd35d1a934a6)

**Comment by Hussein-Mahfouz** [comment]
@Robinlovelace I started on this today but I'm confused with the data. I used the powscar data `(combined_powscar_lines.Rds)`  to get mode share. The data has the following columns:

>  [1] "CSOED_3441"       "POWSC_CSOED"      "destination_type" "COUNTY"           "cyclists"         "public_transport" "foot"            
>  [8] "drivers"          "passengers"       "other"            "primary"          "secondary"        "third_level"      "work"            
> [15] "all_modes"        "all_purposes"     "length_km"        "geometry"   

I grouped the data by CSOED_3441 column to get the totals per origin, but I can't tell which columns should add up to `all_modes`, or if they should add up to all_modes. I tried c`yclists:other` but that is more than all_modes

_Would `cyclists / all_modes` give me the % cycling that we want? If not, what data source do you reccomend for this map?_

**Comment by Robinlovelace** [comment]
Probably best using the original zone level datasets which are open access. I can point you to them. @joeytalbot may be able to point you in the right direction also.

**Comment by Hussein-Mahfouz** [comment]
Yes please could one of you point me to them? Are they in the repo?

**Comment by Robinlovelace** [comment]
Will have a look...

**Comment by Hussein-Mahfouz** [comment]
I tried to find the zone level data used in the landing page. It is based on the `counties.Rds` and `counties.csv` files, as shown [here](https://github.com/ITSLeeds/atumie/blob/4632db4ae6a7202c3aa58385d0b95e53c53f3dd7/index.Rmd#L177). These files are generated from the [proportion-trips-assessed.R script](https://github.com/ITSLeeds/atumie/blob/4632db4ae6a7202c3aa58385d0b95e53c53f3dd7/code/proportion-trips-assessed.R#L345)

The files only have data for Limerick as we are only running it for Limerick. Do we have the data from a national build that I can use to make this map?

**Comment by Robinlovelace** [comment]
> Do we have the data from a national build that I can use to make this map?

Yes but given the number of figures in the paper already I'd say let's pause this one.
